### ISSUE TITLE
Can add inav blackbox csv support ?

### ISSUE THREAD

**Issue by singlag** [kristjanbjarni/osd-subtitles#3]
Can add blackbox csv support ?
user export csv file by Blackbox Explorer and load as opentx log

**Comment by kristjanbjarni** [comment]
I am not sure if the blackbox data actually has any of the telemetry data. I think there is GPS data available but I am not sure if other data like battery voltage, battery draw, RSSI or altitude is in the log data. I currently don't have a iNav craft available to test so if you could provide me with an iNav blackbox log to or point me to some log file available somewhere, then I could take a look if this is feasible.

**Comment by singlag** [comment]
> I am not sure if the blackbox data actually has any of the telemetry data. I think there is GPS data available but I am not sure if other data like battery voltage, battery draw, RSSI or altitude is in the log data. I currently don't have a iNav craft available to test so if you could provide me with an iNav blackbox log to or point me to some log file available somewhere, then I could take a look if this is feasible.

sorry for the late reply, uploaded blackbox csv file to gdrive (exported to csv by Betaflight Blackbox Explorer)
https://drive.google.com/file/d/1xQfruwvwYGGZRqqsCFXl0MAK98Qnm_Sg/view?usp=sharing

**Comment by kristjanbjarni** [comment]
I started to look into this. The data that seems can be used from the log are BaroAlt, rssi and vbat, although I am not sure what is the range of the values exactly. There is no GPS data in the file, which is the most important one. 
Looking at https://github.com/cleanflight/blackbox-tools it seems that the default export to csv doesn't  include the GPS data. The command line program has this option:

--merge-gps              Merge GPS data into the main CSV log file instead of writing it separately

So I am thinking the data wasn't exported with the csv file. Could you maybe share the original blackbox data? or try to export the GPS data with the csv file?

**Comment by singlag** [comment]
> I started to look into this. The data that seems can be used from the log are BaroAlt, rssi and vbat, although I am not sure what is the range of the values exactly. There is no GPS data in the file, which is the most important one. Looking at https://github.com/cleanflight/blackbox-tools it seems that the default export to csv doesn't include the GPS data. The command line program has this option:
> 
> --merge-gps Merge GPS data into the main CSV log file instead of writing it separately
> 
> So I am thinking the data wasn't exported with the csv file. Could you maybe share the original blackbox data? or try to export the GPS data with the csv file?

Hi, here is the original blackbox data
https://drive.google.com/file/d/1klJTZr3io65WlEKhSTce0C6atFcMrKtv/view?usp=sharing

**Comment by kristjanbjarni** [comment]
Added support for reading some elements of iNav blackbox log. Needs to use the [iNav Blackbox tools](https://github.com/iNavFlight/blackbox-tools) to export the CSV file with GPS information. Try it out and let me know how it goes.

**Comment by singlag** [comment]
> Added support for reading some elements of iNav blackbox log. Needs to use the [iNav Blackbox tools](https://github.com/iNavFlight/blackbox-tools) to export the CSV file with GPS information. More information in the [howto](https://kristjanbjarni.github.io/osd-subtitles/docs/howto.html). Try it out and let me know how it goes.

thx, it work but have some problem
1) Gps speed : default export is m/s (GPS_speed (m/s)), if using-"-unit-gps-speed kph" option, it change to GPS_speed (km/h) at line1 and cause "Gps speed" missing 
2) Missing Throttle position in csv file : can use "motor[0]" as Throttle position ?

**Comment by kristjanbjarni** [comment]
1. Fixed GPS speed was not converted from m/s, should work now with defaults options
2. Added throttle position using motor[0]
3. Other fixes and simplifications
