### ISSUE TITLE
Cannot read properties of null (reading 'startsWith')

### ISSUE THREAD

**Issue by Myllerman** [kristjanbjarni/osd-subtitles#4]
When i try to open a .csv log in any browser i get this message popup "Cannot read properties of null (reading 'startsWith')"
and nothing more happens. I am on Windows 11.

**Comment by Myllerman** [comment]
I found the problem! I did not have logging on all the sensors only a some of them. I guess the program errored when not finding those in the csv file.

**Comment by kristjanbjarni** [comment]
That's Great. I also made some minor changes to better handle missing sensor values.
